import csv
from pathlib import Path

prices = {}
with open("scripts/data/initial-prices.csv", encoding="utf-8-sig", newline="") as f:
    for row in csv.DictReader(f):
        prices[row["name"]] = row["avg_price"]

records = [
    ("Tavuk Göğsü", "meat_fish", False, "chicken breast raw"),
    ("Tavuk But", "meat_fish", False, "chicken thigh raw"),
    ("Hindi Göğsü", "meat_fish", False, "turkey breast raw"),
    ("Hindi But", "meat_fish", False, "turkey thigh raw"),
    ("Dana Kıyma", "meat_fish", False, "ground beef lean raw"),
    ("Dana Antrikot", "meat_fish", False, "beef ribeye steak raw"),
    ("Dana Biftek", "meat_fish", False, "beef sirloin steak raw"),
    ("Dana Bonfile", "meat_fish", False, "beef tenderloin raw"),
    ("Kuzu But", "meat_fish", False, "lamb leg raw"),
    ("Kuzu Pirzola", "meat_fish", False, "lamb chop raw"),
    ("Somon Norveç", "meat_fish", False, "atlantic salmon raw"),
    ("Somon Yerli", "meat_fish", False, "pink salmon raw"),
    ("Ton Balığı", "meat_fish", True, "tuna canned in water drained solids"),
    ("Sardalya", "meat_fish", False, "sardine raw"),
    ("Uskumru", "meat_fish", False, "mackerel raw"),
    ("Hamsi", "meat_fish", False, "anchovy raw"),
    ("Levrek", "meat_fish", False, "sea bass raw"),
    ("Çipura", "meat_fish", False, "sea bream raw"),
    ("Yumurta", "dairy_eggs", False, "egg whole raw"),
    ("Yumurta Akı", "dairy_eggs", False, "egg white raw"),
    ("Süt", "dairy_eggs", False, "milk whole"),
    ("Yarım Yağlı Süt", "dairy_eggs", False, "milk reduced fat 2%"),
    ("Yağsız Süt", "dairy_eggs", False, "milk nonfat"),
    ("Yoğurt", "dairy_eggs", False, "yogurt plain whole milk"),
    ("Süzme Yoğurt", "dairy_eggs", False, "greek yogurt plain whole milk"),
    ("Greek Yoğurt", "dairy_eggs", False, "greek yogurt plain nonfat"),
    ("Kefir", "dairy_eggs", False, "kefir plain lowfat"),
    ("Ayran", "dairy_eggs", False, "cultured buttermilk lowfat"),
    ("Lor", "dairy_eggs", False, "ricotta cheese part skim"),
    ("Süzme Peynir", "dairy_eggs", True, "cream cheese low fat"),
    ("Beyaz Peynir", "dairy_eggs", False, "feta cheese"),
    ("Kaşar", "dairy_eggs", True, "kashkaval cheese"),
    ("Mozzarella", "dairy_eggs", True, "mozzarella cheese whole milk"),
    ("Cheddar", "dairy_eggs", True, "cheddar cheese"),
    ("Cottage Cheese", "dairy_eggs", False, "cottage cheese lowfat"),
    ("Labne", "dairy_eggs", True, "labneh"),
    ("Tereyağı", "dairy_eggs", True, "butter salted"),
    ("Kırmızı Mercimek", "legumes_grains", False, "red lentils dry"),
    ("Yeşil Mercimek", "legumes_grains", False, "lentils raw"),
    ("Nohut", "legumes_grains", False, "chickpeas raw"),
    ("Kuru Fasulye", "legumes_grains", False, "white beans raw"),
    ("Barbunya", "legumes_grains", False, "cranberry beans raw"),
    ("Börülce", "legumes_grains", False, "cowpeas raw"),
    ("Bezelye", "legumes_grains", False, "split peas dry"),
    ("İç Bakla", "legumes_grains", False, "fava beans dry"),
    ("Soya Fasulyesi", "legumes_grains", False, "soybeans mature seeds raw"),
    ("Sarı Mercimek", "legumes_grains", False, "yellow lentils dry"),
    ("Yulaf", "legumes_grains", False, "oats rolled dry"),
    ("Pirinç", "legumes_grains", False, "rice white long grain raw"),
    ("Baldo Pirinç", "legumes_grains", False, "rice white medium grain raw"),
    ("Jasmin Pirinç", "legumes_grains", False, "rice jasmine raw"),
    ("Bulgur", "legumes_grains", False, "bulgur dry"),
    ("Kinoa", "legumes_grains", False, "quinoa raw"),
    ("Karabuğday", "legumes_grains", False, "buckwheat groats raw"),
    ("Arpa", "legumes_grains", False, "barley hulled raw"),
    ("Mısır", "legumes_grains", False, "corn grain yellow dried"),
    ("Mısır Unu", "legumes_grains", True, "corn flour whole grain"),
    ("İrmik", "legumes_grains", True, "semolina"),
    ("Kuskus", "legumes_grains", True, "couscous dry"),
    ("Tam Buğday Unu", "legumes_grains", True, "whole wheat flour"),
    ("Siyez", "legumes_grains", False, "einkorn wheat raw"),
    ("Tam Buğday Makarna", "legumes_grains", True, "whole wheat spaghetti dry"),
    ("Beyaz Makarna", "legumes_grains", True, "spaghetti dry enriched"),
    ("Erişte", "legumes_grains", True, "egg noodles dry"),
    ("Beyaz Ekmek", "legumes_grains", True, "white bread"),
    ("Tam Buğday Ekmek", "legumes_grains", True, "whole wheat bread"),
    ("Çavdar Ekmeği", "legumes_grains", True, "rye bread"),
    ("Lavaş", "legumes_grains", True, "lavash bread"),
    ("Yufka", "legumes_grains", True, "phyllo dough"),
    ("Tortilla", "legumes_grains", True, "flour tortilla"),
    ("Patates", "vegetables", False, "potato raw"),
    ("Tatlı Patates", "vegetables", False, "sweet potato raw"),
    ("Havuç", "vegetables", False, "carrots raw"),
    ("Kabak", "vegetables", False, "zucchini raw"),
    ("Patlıcan", "vegetables", False, "eggplant raw"),
    ("Domates", "vegetables", False, "tomatoes raw"),
    ("Salatalık", "vegetables", False, "cucumber with peel raw"),
    ("Kapya Biber", "vegetables", False, "sweet red pepper raw"),
    ("Soğan", "vegetables", False, "onions raw"),
    ("Sarımsak", "vegetables", False, "garlic raw"),
    ("Pırasa", "vegetables", False, "leeks raw"),
    ("Ispanak", "vegetables", False, "spinach raw"),
    ("Brokoli", "vegetables", False, "broccoli raw"),
    ("Karnabahar", "vegetables", False, "cauliflower raw"),
    ("Lahana", "vegetables", False, "cabbage green raw"),
    ("Mor Lahana", "vegetables", False, "cabbage red raw"),
    ("Brüksel Lahanası", "vegetables", False, "brussels sprouts raw"),
    ("Marul", "vegetables", False, "romaine lettuce raw"),
    ("Roka", "vegetables", False, "arugula raw"),
    ("Dereotu", "vegetables", False, "dill weed fresh"),
    ("Semizotu", "vegetables", False, "purslane raw"),
    ("Mantar", "vegetables", False, "mushrooms white raw"),
    ("Kereviz", "vegetables", False, "celeriac raw"),
    ("Pancar", "vegetables", False, "beets raw"),
    ("Turp", "vegetables", False, "radishes raw"),
    ("Enginar", "vegetables", False, "artichoke raw"),
    ("Bamya", "vegetables", False, "okra raw"),
    ("Taze Fasulye", "vegetables", False, "green beans raw"),
    ("Avokado", "other", False, "avocado raw"),
    ("Muz", "other", False, "banana raw"),
    ("Elma", "other", False, "apple raw with skin"),
    ("Armut", "other", False, "pear raw"),
    ("Portakal", "other", False, "orange raw"),
    ("Mandalina", "other", False, "tangerine raw"),
    ("Greyfurt", "other", False, "grapefruit raw"),
    ("Limon", "other", False, "lemon raw"),
    ("Nar", "other", False, "pomegranate raw"),
    ("Üzüm", "other", False, "grapes raw"),
    ("Çilek", "other", False, "strawberries raw"),
    ("Yaban Mersini", "other", False, "blueberries raw"),
    ("Ahududu", "other", False, "raspberries raw"),
    ("Kivi", "other", False, "kiwifruit raw"),
    ("Ananas", "other", False, "pineapple raw"),
    ("Mango", "other", False, "mango raw"),
    ("Şeftali", "other", False, "peaches raw"),
    ("Kuru Kayısı", "other", False, "apricots dried"),
    ("Kuru İncir", "other", False, "figs dried"),
    ("Hurma", "other", False, "dates medjool"),
    ("Karpuz", "other", False, "watermelon raw"),
    ("Badem", "other", False, "almonds"),
    ("Ceviz", "other", False, "walnuts"),
    ("Fındık", "other", False, "hazelnuts"),
    ("Yer Fıstığı", "other", False, "peanuts all types raw"),
    ("Kaju", "other", False, "cashew nuts raw"),
    ("Antep Fıstığı", "other", False, "pistachio nuts raw"),
    ("Ay Çekirdeği", "other", False, "sunflower seed kernels dried"),
    ("Kabak Çekirdeği", "other", False, "pumpkin seed kernels dried"),
    ("Chia", "other", False, "chia seeds dried"),
    ("Keten Tohumu", "other", False, "flaxseed"),
    ("Susam", "other", False, "sesame seeds"),
    ("Tahin", "other", True, "tahini sesame butter"),
    ("Zeytinyağı", "other", True, "olive oil"),
    ("Ayçiçek Yağı", "other", True, "sunflower oil"),
    ("Hindistan Cevizi Yağı", "other", True, "coconut oil"),
    ("Bal", "other", False, "honey"),
    ("Salça", "other", True, "tomato paste"),
    ("Fıstık Ezmesi", "other", True, "peanut butter"),
]

if len(records) != 137:
    raise SystemExit(f"Record count mismatch: {len(records)}")

missing_prices = [name for name, *_ in records if name not in prices]
if missing_prices:
    raise SystemExit("Missing prices: " + ", ".join(missing_prices))

output_path = Path("scripts/data/food-manifest.csv")
with output_path.open("w", encoding="utf-8-sig", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["name", "category", "is_processed", "usda_query", "avg_price"])
    for name, category, is_processed, usda_query in records:
        writer.writerow([name, category, str(is_processed).lower(), usda_query, prices[name]])

print(output_path)
print(len(records))
